### ISSUE TITLE
Error encountered executing install script on GCP VM

### ISSUE THREAD

**Issue by yoke2** [natbusa/databox#1]
Hi,

I set up a VM with the following on GCP:

- N1-standard-8
- Ubuntu 18.04 LTS
- 50GB standard persistent disk

Then I tried to perform the installation below as per Step 1 and received errors:

- Click on SSH
- In command line type `git clone https://github.com/natbusa/databox.git`
- `cd databox` 
- `sudo bin/install.sh` [did not see scripts/ folder in repo, so used bin/install.sh]
- Error received.

Please see Google Slides link for the error screenshot on slide 3: https://docs.google.com/presentation/d/1ohSuH0nH5Ng2YV3N26AjVaFmk8ky7f-vj5Q3ce8tyRg/edit?usp=sharing

I tried to further follow step 2 but get errors as well. Please see slide 4 in the link above.

Please advise.

**Comment by waterstar** [comment]
check out the pull request. it should work if you make the changes locally.
https://github.com/natbusa/databox/pull/2

**Comment by natbusa** [comment]
solved.
